name: Code Quality
on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  code-quality-linux-x86_64:
    name: libkrun (Linux x86_64)
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup build environment
        uses: ./.github/actions/setup-build-env
      
      - name: Create a fake init
        run: touch init/init
      
      - name: Clippy (default)
        run: cargo clippy --locked -- -D warnings
      
      - name: Clippy (amd-sev)
        run: cargo clippy --locked --features amd-sev -- -D warnings
      
      - name: Clippy (tdx)
        run: cargo clippy --locked --features tdx -- -D warnings
      
      - name: Clippy (net+blk+gpu+input)
        run: cargo clippy --locked --features net,blk,gpu,input -- -D warnings

  code-quality-linux-aarch64:
    name: libkrun (Linux aarch64)
    runs-on: ubuntu-26.04-arm
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup build environment
        uses: ./.github/actions/setup-build-env
      
      - name: Create a fake init
        run: touch init/init
      
      - name: Clippy (default)
        run: cargo clippy --locked -- -D warnings
      
      - name: Clippy (net+blk+gpu+input)
        run: cargo clippy --locked --features net,blk,gpu,input -- -D warnings

  code-quality-macos:
    name: libkrun (macOS aarch64)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup build environment
        uses: ./.github/actions/setup-build-env
      
      - name: Create a fake init
        run: touch init/init
      
      - name: Clippy (gpu)
        run: cargo clippy --locked --features gpu -- -D warnings
        env:
          KRUN_INIT_BINARY_PATH: ${{ github.workspace }}/init/init
